server:
  port: 8766

sidecar:
  port: 8000
  health-uri: http://localhost:${sidecar.port}/sidecar/

spring:
  application:
    name: py-sidecar

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:10010/eureka/
